# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
