# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160704_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairExtention',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
