# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hairextention'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeratinBonds',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MicroRings',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TapedHairExtentions',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weave',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
