# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160725_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weave',
            name='price',
        ),
    ]
