# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_weave_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brow',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hairdressing',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lash',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MakeUp',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nail',
            fields=[
                ('type', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
