# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_brow_hairdressing_lash_makeup_nail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lash',
            new_name='Lash_Brow',
        ),
        migrations.DeleteModel(
            name='Brow',
        ),
    ]
